-- ============================================================================
--  Loja — estrutura do banco e regras de acesso (Supabase / PostgreSQL)
--
--  COMO USAR
--    1. Abra o painel do Supabase > SQL Editor > New query
--    2. Cole este arquivo inteiro e clique em "Run"
--    3. Cadastre o administrador (instruções no final do arquivo)
--
--  Rodar de novo não quebra nada: o arquivo foi escrito para ser reaplicado
--  quantas vezes forem necessárias (tabelas usam IF NOT EXISTS e as regras
--  são apagadas antes de recriadas).
--
--  POR QUE ISSO IMPORTA
--    A chave "anon" da loja fica visível no código da página — é assim mesmo.
--    Quem realmente impede um visitante de apagar seus produtos são as regras
--    de acesso (RLS) deste arquivo. Sem elas, a chave pública vira acesso
--    total ao banco.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. TABELAS
-- ----------------------------------------------------------------------------

-- Quem pode administrar a loja. Uma linha por administrador.
-- Estar nesta tabela é o que distingue um admin de um usuário comum.
create table if not exists public.admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  criado_em  timestamptz not null default now()
);

create table if not exists public.catalogos (
  id    bigint primary key,
  nome  text not null
);

create table if not exists public.produtos (
  id             bigint primary key,
  nome           text not null,
  descricao      text not null default '',
  preco          numeric(12,2) not null default 0,
  estoque        integer not null default 0,
  emoji          text not null default '📦',
  imagem_url     text not null default '',
  -- Lista de ids de catálogo, ex.: [1, 3]. O código lê com Array.isArray().
  catalogos      jsonb not null default '[]'::jsonb,
  -- Texto livre mostrado na tela "Ver detalhes" (campo "Observação").
  detalhes       text not null default '',
  atualizado_em  timestamptz not null default now()
);

-- Para quem já tinha a tabela criada antes deste campo existir.
-- Em banco novo não faz nada; em banco existente, adiciona a coluna.
alter table public.produtos add column if not exists detalhes text not null default '';

-- Promoção: "a partir de" + "~~R$ 142,00~~ por R$ 134,00".
-- preco_antigo vazio (null) = produto sem preço riscado.
alter table public.produtos add column if not exists preco_antigo numeric(12,2);
alter table public.produtos add column if not exists a_partir_de boolean not null default false;

-- Uma versão anterior deste arquivo criava as colunas incluso/nao_incluso,
-- que foram substituídas pelo campo único "Observação". Se elas existirem no
-- seu banco, as linhas abaixo as removem. Só apague estas duas linhas se
-- quiser conservá-las por algum motivo.
alter table public.produtos drop column if exists incluso;
alter table public.produtos drop column if exists nao_incluso;

-- Ficha dos clientes. A senha NÃO fica aqui: quem cuida dela é o Supabase
-- Auth, que guarda só o hash. Esta tabela tem apenas os dados de exibição,
-- ligados à conta pelo mesmo user_id.
create table if not exists public.clientes (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  nome       text not null,
  email      text not null,
  criado_em  timestamptz not null default now()
);

create table if not exists public.pedidos (
  id                bigint primary key,
  numero            text not null,
  criado_em         timestamptz not null default now(),
  cliente_nome      text not null,
  cliente_email     text not null,
  cliente_cep       text not null default '',
  tipo_recebimento  text not null,
  metodo_pagamento  text not null,
  -- Lista de itens do pedido, cada um um objeto JSON.
  itens             jsonb not null default '[]'::jsonb,
  total             numeric(12,2) not null default 0,
  status            text not null default 'Pendente',
  -- Dono do pedido, quando a compra foi feita com conta. Fica nulo em compra
  -- sem cadastro, que continua permitida.
  cliente_id        uuid references auth.users(id) on delete set null
);

alter table public.pedidos add column if not exists cliente_id uuid references auth.users(id) on delete set null;

-- A tela de pedidos ordena por data; sem índice isso fica lento conforme a
-- loja cresce.
create index if not exists pedidos_criado_em_idx
  on public.pedidos (criado_em desc);

-- Avisos para o administrador: conta criada, item no carrinho, cliente
-- chegando no pagamento. Quem grava aqui é o navegador do visitante; quem lê
-- é só o administrador.
create table if not exists public.eventos (
  id         bigint generated by default as identity primary key,
  tipo       text not null,
  titulo     text not null,
  detalhe    text not null default '',
  cliente    text not null default '',
  criado_em  timestamptz not null default now(),
  lido       boolean not null default false
);

create index if not exists eventos_criado_em_idx
  on public.eventos (criado_em desc);


-- ----------------------------------------------------------------------------
-- 2. FUNÇÃO AUXILIAR: "quem está pedindo é administrador?"
--
--    Precisa ser SECURITY DEFINER para poder consultar a tabela admins sem
--    passar pelas regras dela. Sem isso, uma regra que consulta admins
--    dispararia a regra de admins, que consulta admins... (recursão infinita,
--    erro 42P17 no Supabase).
--
--    O search_path fixo evita que alguém crie uma tabela "admins" falsa em
--    outro schema e engane a função.
-- ----------------------------------------------------------------------------

create or replace function public.eh_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admins where user_id = auth.uid()
  );
$$;

revoke all on function public.eh_admin() from public;
grant execute on function public.eh_admin() to anon, authenticated;


-- ----------------------------------------------------------------------------
-- 2b. AUTOMAÇÕES NO SERVIDOR
-- ----------------------------------------------------------------------------

-- Toda conta criada no Supabase Auth ganha, na mesma hora, a sua ficha em
-- public.clientes. Fazer isso aqui, e não no navegador, garante que o
-- cliente apareça para o administrador mesmo que a página feche no meio do
-- cadastro ou que o projeto exija confirmação por e-mail (caso em que o
-- navegador ainda não tem permissão para gravar a ficha).
create or replace function public.criar_ficha_cliente()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.clientes (user_id, nome, email)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data->>'nome'), ''), new.email, 'Sem nome'), 200),
    left(coalesce(new.email, ''), 320)
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists auth_cria_ficha_cliente on auth.users;
create trigger auth_cria_ficha_cliente
  after insert on auth.users
  for each row execute function public.criar_ficha_cliente();

-- Contas que já existiam antes deste gatilho também ganham ficha.
-- Administradores ficam de fora: não são clientes da loja.
insert into public.clientes (user_id, nome, email)
select u.id,
       left(coalesce(nullif(trim(u.raw_user_meta_data->>'nome'), ''), u.email, 'Sem nome'), 200),
       left(coalesce(u.email, ''), 320)
from auth.users u
where not exists (select 1 from public.admins a where a.user_id = u.id)
on conflict (user_id) do nothing;

-- Baixa de estoque feita pelo servidor quando um pedido é gravado. O
-- navegador do cliente não tem (nem deve ter) permissão para alterar a
-- tabela de produtos; antes, ele tentava e falhava sem que ninguém visse.
-- Quantidades inválidas ou negativas são ignoradas, para que ninguém consiga
-- AUMENTAR o estoque mandando um pedido com quantidade negativa.
create or replace function public.baixar_estoque_do_pedido()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  item jsonb;
  qtd  integer;
begin
  for item in select * from jsonb_array_elements(new.itens) loop
    begin
      qtd := (item->>'qtd')::integer;
    exception when others then
      qtd := null;
    end;
    if qtd is null or qtd <= 0 then
      continue;
    end if;
    update public.produtos
       set estoque = greatest(estoque - qtd, 0),
           atualizado_em = now()
     where id = (item->>'produtoId')::bigint;
  end loop;
  return new;
end;
$$;

drop trigger if exists pedidos_baixa_estoque on public.pedidos;
create trigger pedidos_baixa_estoque
  after insert on public.pedidos
  for each row execute function public.baixar_estoque_do_pedido();


-- ----------------------------------------------------------------------------
-- 3. LIGAR AS REGRAS DE ACESSO
--
--    Com RLS ligado e nenhuma regra correspondente, o padrão é NEGAR.
--    Tudo que não estiver liberado abaixo fica bloqueado.
-- ----------------------------------------------------------------------------

alter table public.admins    enable row level security;
alter table public.catalogos enable row level security;
alter table public.produtos  enable row level security;
alter table public.pedidos   enable row level security;
alter table public.eventos   enable row level security;
alter table public.clientes  enable row level security;


-- ----------------------------------------------------------------------------
-- 4. REGRAS
-- ----------------------------------------------------------------------------

-- ---- admins ----------------------------------------------------------------
-- Cada pessoa logada enxerga no máximo a própria linha. É exatamente disso
-- que a loja depende: ela consulta esta tabela e, se voltar alguma linha,
-- trata a pessoa como administradora (index.html, confirmarSeEhAdmin).
-- Um usuário comum recebe zero linhas e não entra.
--
-- Ninguém se promove sozinho: não há regra de INSERT/UPDATE/DELETE aqui.
-- Administradores são cadastrados pelo painel do Supabase (veja o final).
drop policy if exists "admin ve a propria linha" on public.admins;
create policy "admin ve a propria linha"
  on public.admins for select
  to authenticated
  using (user_id = auth.uid());


-- ---- catalogos -------------------------------------------------------------
-- Qualquer visitante lê (a vitrine precisa disso). Só admin altera.
drop policy if exists "catalogos leitura publica" on public.catalogos;
create policy "catalogos leitura publica"
  on public.catalogos for select
  to anon, authenticated
  using (true);

drop policy if exists "catalogos escrita admin" on public.catalogos;
create policy "catalogos escrita admin"
  on public.catalogos for all
  to authenticated
  using (public.eh_admin())
  with check (public.eh_admin());


-- ---- produtos --------------------------------------------------------------
drop policy if exists "produtos leitura publica" on public.produtos;
create policy "produtos leitura publica"
  on public.produtos for select
  to anon, authenticated
  using (true);

drop policy if exists "produtos escrita admin" on public.produtos;
create policy "produtos escrita admin"
  on public.produtos for all
  to authenticated
  using (public.eh_admin())
  with check (public.eh_admin());


-- ---- clientes --------------------------------------------------------------
-- A pessoa cria e enxerga apenas a própria ficha; o administrador enxerga
-- todas. Ninguém consegue listar os clientes uns dos outros.
drop policy if exists "cliente cria a propria ficha" on public.clientes;
create policy "cliente cria a propria ficha"
  on public.clientes for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and length(nome) between 1 and 200
    and length(email) between 3 and 320
  );

drop policy if exists "cliente le a propria ficha" on public.clientes;
create policy "cliente le a propria ficha"
  on public.clientes for select
  to authenticated
  using (user_id = auth.uid() or public.eh_admin());

drop policy if exists "cliente atualiza a propria ficha" on public.clientes;
create policy "cliente atualiza a propria ficha"
  on public.clientes for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());


-- ---- pedidos ---------------------------------------------------------------
-- O ponto mais delicado da loja.
--
-- LEITURA: só admin. Pedidos têm nome, e-mail e CEP de clientes — se um
-- visitante pudesse ler esta tabela, leria os dados de todos os compradores.
-- Repare que NÃO existe regra de select para "anon" abaixo. É de propósito.
-- O cliente logado enxerga os próprios pedidos (aba "Meus Pedidos") e mais
-- nada. Quem comprou sem cadastro não tem como consultar depois: não existe
-- dono para comparar.
drop policy if exists "pedidos leitura admin" on public.pedidos;
create policy "pedidos leitura admin"
  on public.pedidos for select
  to authenticated
  using (public.eh_admin() or cliente_id = auth.uid());

-- CRIAÇÃO: qualquer visitante, senão ninguém consegue finalizar uma compra.
-- O with check limita o estrago: o pedido entra obrigatoriamente como
-- "Pendente" e com valores coerentes. Um pedido não pode nascer já "Pago".
drop policy if exists "pedidos criacao publica" on public.pedidos;
create policy "pedidos criacao publica"
  on public.pedidos for insert
  to anon, authenticated
  with check (
    status = 'Pendente'
    and total >= 0
    and length(cliente_nome) between 1 and 200
    and length(cliente_email) between 3 and 320
    and length(cliente_cep) <= 20
    and jsonb_typeof(itens) = 'array'
    and jsonb_array_length(itens) between 1 and 200
    -- Estes três campos são exibidos na tela do administrador. Limitá-los aos
    -- valores que a loja realmente usa impede que alguém grave HTML aqui para
    -- ser executado no navegador de quem vê os pedidos.
    and numero ~ '^[A-Za-z0-9#/-]{1,30}$'
    and metodo_pagamento in ('pix','cartao','dinheiro')
    and tipo_recebimento in ('retirada','entrega')
    -- Ou o pedido é anônimo, ou é da própria pessoa. Impede que alguém
    -- registre pedidos no nome de outro cliente.
    and (cliente_id is null or cliente_id = auth.uid())
  );

-- ALTERAÇÃO E EXCLUSÃO: só admin (confirmar pagamento, cancelar, excluir).
-- Sem a regra de update abaixo, o visitante também não consegue sobrescrever
-- um pedido existente passando um id que já existe.
drop policy if exists "pedidos alteracao admin" on public.pedidos;
create policy "pedidos alteracao admin"
  on public.pedidos for update
  to authenticated
  using (public.eh_admin())
  with check (public.eh_admin());

drop policy if exists "pedidos exclusao admin" on public.pedidos;
create policy "pedidos exclusao admin"
  on public.pedidos for delete
  to authenticated
  using (public.eh_admin());


-- ---- eventos (notificações do administrador) -------------------------------
-- O visitante só grava. Ele não lê nem apaga: se lesse, veria o que os outros
-- clientes estão fazendo na loja.
drop policy if exists "eventos criacao publica" on public.eventos;
create policy "eventos criacao publica"
  on public.eventos for insert
  to anon, authenticated
  with check (
    tipo in ('conta','conta_invalida','carrinho','pagamento','pedido')
    and length(titulo)  between 1 and 120
    and length(detalhe) <= 500
    and length(cliente) <= 200
    and lido = false
  );

drop policy if exists "eventos leitura admin" on public.eventos;
create policy "eventos leitura admin"
  on public.eventos for select
  to authenticated
  using (public.eh_admin());

-- Marcar como lido.
drop policy if exists "eventos alteracao admin" on public.eventos;
create policy "eventos alteracao admin"
  on public.eventos for update
  to authenticated
  using (public.eh_admin())
  with check (public.eh_admin());

drop policy if exists "eventos exclusao admin" on public.eventos;
create policy "eventos exclusao admin"
  on public.eventos for delete
  to authenticated
  using (public.eh_admin());


-- ----------------------------------------------------------------------------
-- 5. FOTOS DOS PRODUTOS (Storage)
--
--    Cria o bucket "fotos" como público: as imagens aparecem na vitrine sem
--    precisar de login. Enviar e apagar arquivo, só admin.
-- ----------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('fotos', 'fotos', true)
on conflict (id) do update set public = true;

drop policy if exists "fotos leitura publica" on storage.objects;
create policy "fotos leitura publica"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'fotos');

drop policy if exists "fotos envio admin" on storage.objects;
create policy "fotos envio admin"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'fotos' and public.eh_admin());

drop policy if exists "fotos alteracao admin" on storage.objects;
create policy "fotos alteracao admin"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'fotos' and public.eh_admin())
  with check (bucket_id = 'fotos' and public.eh_admin());

drop policy if exists "fotos exclusao admin" on storage.objects;
create policy "fotos exclusao admin"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'fotos' and public.eh_admin());


-- ============================================================================
--  DEPOIS DE RODAR ESTE ARQUIVO: cadastrar o administrador
--
--  1) Painel do Supabase > Authentication > Users > "Add user"
--       - Informe e-mail e senha
--       - Marque "Auto Confirm User" (senão o login recusa com
--         "Email not confirmed")
--       - Copie o UUID que aparece na lista de usuários
--
--  2) Volte ao SQL Editor e rode, trocando pelo UUID copiado:
--
--       insert into public.admins (user_id)
--       values ('cole-o-uuid-aqui')
--       on conflict (user_id) do nothing;
--
--  3) Na loja, entre na administração com esse e-mail e senha.
--
--  Para remover um administrador:
--       delete from public.admins where user_id = 'uuid-da-pessoa';
--  (A conta continua existindo, só perde o acesso de administração.)
--
--
--  CONFERINDO SE FICOU SEGURO
--
--  Abra a loja numa janela anônima, SEM fazer login, e no console do
--  navegador (F12) rode:
--
--       await bd.from('pedidos').select('*')
--
--  O esperado é vir uma lista vazia ou um erro de permissão. Se vierem
--  pedidos de verdade, alguma regra não foi aplicada — confira em
--  Authentication > Policies se as quatro tabelas estão com RLS ativo.
--
--
--  LIMITE DESTA ARQUITETURA — vale saber
--
--  A loja funciona só no navegador, sem servidor próprio. Isso significa que
--  o preço e o total do pedido são calculados na máquina do cliente e
--  enviados prontos. Alguém com conhecimento técnico consegue montar uma
--  requisição e registrar um pedido com total errado (ex.: R$ 0,01).
--
--  As regras acima impedem o pior (ninguém lê os dados dos seus clientes,
--  ninguém altera seus produtos, ninguém marca o próprio pedido como pago),
--  mas NÃO têm como garantir o valor: para isso o total precisaria ser
--  recalculado no servidor, numa Edge Function do Supabase.
--
--  Na prática: confira o valor do pedido antes de confirmar o pagamento.
--  Como o status só muda para "Pago" por um administrador, essa conferência
--  já fecha a brecha no dia a dia.
-- ============================================================================
